=== AurelienChoquet/magento2-module-store-locator/etc/addresses.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
/**
 * Default Configuration for Localized Retailer
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future.
 *
 * @category  Smile
 * @package   Smile\Smile_LocalizedRetailer
 * @author    Romain RUAUD <romain.ruaud@smile.fr>
 * @copyright 2016 Smile
 * @license   Apache License Version 2.0
 */
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="format" type="formatDeclaration" minOccurs="1" maxOccurs="unbounded">

                </xs:element>
            </xs:sequence>
        </xs:complexType>

        <xs:unique name="uniqueOptionName">
            <xs:selector xpath="address"/>
            <xs:field xpath="@name"/>
        </xs:unique>
    </xs:element>

    <xs:complexType name="formatDeclaration">
        <xs:sequence>
            <xs:element name="line" type="lineDeclaration" minOccurs="1" maxOccurs="unbounded">

            </xs:element>
        </xs:sequence>

        <xs:attribute name="name" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="lineDeclaration">
        <xs:sequence>
            <xs:element name="element" type="elementDeclaration" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="elementDeclaration">
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="type" type="elementType" use="required"/>
        <xs:attribute name="separator" type="xs:string"/>
    </xs:complexType>

    <xs:simpleType name="elementType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="attribute"/>
            <xs:enumeration value="method"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== AurelienChoquet/magento2-module-store-locator/etc/addresses.xml
<?xml version="1.0"?>
<!--
/**
 * Default Configuration for Localized Retailer
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade this module to newer
 * versions in the future.
 *
 * @category  Smile
 * @package   Smile\Smile_LocalizedRetailer
 * @author    Romain RUAUD <romain.ruaud@smile.fr>
 * @copyright 2016 Smile
 * @license   Apache License Version 2.0
 */
-->
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:module:Smile_StoreLocator:etc/addresses.xsd">
    <format name="default">
        <line>
            <element type="attribute" name="street"/>
        </line>
        <line>
            <element type="attribute" name="postcode"/>
            <element type="attribute" name="city"/>
        </line>
        <line>
            <element type="attribute" name="contact_phone"/>
        </line>
        <line>
            <element type="attribute" name="contact_email"/>
        </line>
    </format>

    <format name="short">
        <line>
            <element type="attribute" name="street"/>
        </line>
        <line>
            <element type="attribute" name="postcode"/>
            <element type="attribute" name="city"/>
        </line>
        <line>
            <element type="attribute" name="contact_phone"/>
        </line>
    </format>
</config>
